### ISSUE TITLE
questions about the porting process

### ISSUE THREAD

**Issue by emma-the-rock** [sailfish-on-gta4xlwifi/docs#3]
Hi, did you had any troubles with rndis/telnet when you started porting hybris-boot?
I tried with halium-boot (ub-ports) and i couldn't get rndis/telnet because the packets the tablet sent (dhcp or any kind) wouldn't reach my pc but the tablet would recieve the dhcp request from my pc. it was quite strange.

**Comment by HengYeDev** [comment]
Yes, I did have some trouble. You need to apply a different USB config in the bootloader. Please see **https://github.com/sailfish-on-gta4xlwifi/hybris-boot/blob/master/init-script#L194-L227**
